# Numpy

### Task 1. Numpy

In [1]:
import numpy as np

In [5]:
a = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])

In [6]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [19]:
mean_a = np.mean(a, axis = 0)

In [20]:
mean_a

array([2. , 8.4])

 ### Task 2. Numpy

In [23]:
a_centered = a - mean_a

In [25]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Task 3. Numpy

In [73]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])

In [86]:
a_centered_sp

8.0

In [106]:
a_centered_sp/(a_centered.shape[0] - 1)

2.0

### Task 4. Numpy

In [93]:
at = a.T

In [94]:
at

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [104]:
b = np.cov(at)

In [105]:
b[0][1]

2.0

# Pandas

### Task 1. Pandas

In [107]:
import pandas as pd

In [114]:
authors = pd.DataFrame({'author_id':[1, 2, 3],
                        'author_name':['Тургенев', 'Чехов', 'Островский']}, columns=['author_id', 'author_name'])

In [115]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [116]:
author_id = [1, 1, 1, 2, 2, 3, 3]

In [117]:
book_title = ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий',
              'Дама с собачкой', 'Гроза', 'Таланты и поклонники']

In [118]:
price = [450, 300, 350, 500, 450, 370, 290]

In [119]:
books = pd.DataFrame({'author_id': author_id, 'book_title': book_title, 'price': price},
                     columns=['author_id', 'book_title','price'])

In [120]:
books

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

### Task 2. Pandas

In [132]:
authors_price = pd.merge(authors, books, on = 'author_id', how = 'outer')

In [133]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

### Task 3. Pandas

Variant 1

In [144]:
authors_price = authors_price.sort_values('price', ascending=False)

In [145]:
authors_price

author_id author_name            book_title  price
6          2       Чехов      Толстый и тонкий    500
4          1    Тургенев           Отцы и дети    450
5          2       Чехов       Дама с собачкой    450
3          3  Островский                 Гроза    370
2          1    Тургенев     Дворянское гнездо    350
1          1    Тургенев                 Рудин    300
0          3  Островский  Таланты и поклонники    290

In [146]:
authors_price = authors_price.reset_index(drop=True)

In [207]:
authors_price

author_id author_name            book_title  price
0          2       Чехов      Толстый и тонкий    500
1          1    Тургенев           Отцы и дети    450
2          2       Чехов       Дама с собачкой    450
3          3  Островский                 Гроза    370
4          1    Тургенев     Дворянское гнездо    350
5          1    Тургенев                 Рудин    300
6          3  Островский  Таланты и поклонники    290

In [157]:
authors_price.loc[0:4, :]

author_id author_name         book_title  price
0          2       Чехов   Толстый и тонкий    500
1          1    Тургенев        Отцы и дети    450
2          2       Чехов    Дама с собачкой    450
3          3  Островский              Гроза    370
4          1    Тургенев  Дворянское гнездо    350

Variant 2

In [224]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price    cover
0          2       Чехов   Толстый и тонкий    500   мягкая
1          1    Тургенев        Отцы и дети    450   мягкая
2          2       Чехов    Дама с собачкой    450   мягкая
3          3  Островский              Гроза    370  твердая
4          1    Тургенев  Дворянское гнездо    350  твердая

### Task 4. Pandas

In [205]:
authors_stat = authors_price.groupby('author_name').agg({'price':['min', 'max', 'mean']})
authors_stat

price                 
              min  max        mean
author_name                       
Островский    290  370  330.000000
Тургенев      300  450  366.666667
Чехов         450  500  475.000000

### Task 5. Pandas

In [226]:
authors_price['cover'] = ['мягкая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
authors_price

author_id author_name            book_title  price    cover
0          2       Чехов      Толстый и тонкий    500   мягкая
1          1    Тургенев           Отцы и дети    450   мягкая
2          2       Чехов       Дама с собачкой    450   мягкая
3          3  Островский                 Гроза    370  твердая
4          1    Тургенев     Дворянское гнездо    350  твердая
5          1    Тургенев                 Рудин    300   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [210]:
?pd.pivot_table

In [228]:
book_info = pd.pivot_table(authors_price, values='price', index='author_name',
                           columns='cover', aggfunc='sum', fill_value=0, dropna=False)
book_info

cover        мягкая  твердая
author_name                 
Островский      290      370
Тургенев        750      350
Чехов           950        0

In [230]:
book_info.to_pickle('book_info.pkl')
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

cover        мягкая  твердая
author_name                 
Островский      290      370
Тургенев        750      350
Чехов           950        0